

name: Run unit test

on: 
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    runUnitTestJob:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                nodeV: [16.x,18.x]
        steps:
            -   name: Checkout the repo
                uses: actions/checkout@v3
            -   name: node-js setup
                uses: actions/setup-node@v3
                with:
                    node-version: ${{matrix.nodeV}}
            -   name: pnpm setup
                uses: pnpm/action-setup@v2
                with:
                    version: 8
            -   name: install deps
                run: pnpm install
            -   name: Run testings
                run : pnpm test:unit
    
